/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.Inventario;

/**
 *
 * @author ferna
 */
public class VistaInventario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaInventario.class.getName());

    /**
     * Creates new form VistaInventario
     */
    public VistaInventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAgregarProducto = new javax.swing.JButton();
        btnBuscarProducto = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        btnRegVenta = new javax.swing.JButton();
        btnGenerarReporte = new javax.swing.JButton();
        btnVerDatosEstudiante = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menú de gestión de productos");

        btnAgregarProducto.setText("Agregar Producto");

        btnBuscarProducto.setText("Buscar Producto");

        btnEliminarProducto.setText("Eliminar Producto");

        btnRegVenta.setText("Registrar Venta");

        btnGenerarReporte.setText("Generar Reporte");

        btnVerDatosEstudiante.setText("Ver Datos Estudiante");

        btnSalir.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarProducto)
                            .addComponent(btnAgregarProducto)
                            .addComponent(btnEliminarProducto)
                            .addComponent(btnRegVenta)
                            .addComponent(btnGenerarReporte)
                            .addComponent(btnVerDatosEstudiante)
                            .addComponent(btnSalir))))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerarReporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerDatosEstudiante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //Instanciamos el modelo, la vista y el controlador
        VistaInventario vista = new VistaInventario();
        //El modelo se encarga de gestionar los datos, en este caso el inventario de productos
        Inventario inventario = new Inventario();
        //El controlador se encarga de manejar la lógica de la aplicación, interactuando entre la vista y el modelo
        controlador.ControladorInventario controlador = new controlador.ControladorInventario(vista, inventario);
        //Iniciamos la aplicación mostrando la vista
        controlador.iniciar();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarProducto;
    public javax.swing.JButton btnBuscarProducto;
    public javax.swing.JButton btnEliminarProducto;
    public javax.swing.JButton btnGenerarReporte;
    public javax.swing.JButton btnRegVenta;
    public javax.swing.JButton btnSalir;
    public javax.swing.JButton btnVerDatosEstudiante;
    public javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
